### ISSUE TITLE
V2.17.0.4二人答题出错后一直卡在80分不动啦

### ISSUE THREAD

**Issue by 85524365** [james-bond-007/lovexuexi#11]
感谢大神的付出，辛苦啦
系统安卓8.0
1、刚发现V2.17.0.4二人答某题出错后，一直卡在80分不动啦，直到别人答100分。
https://ftp.bmp.ovh/imgs/2020/10/dd9551d8efd1c43e.jpg
<img src = 'https://ftp.bmp.ovh/imgs/2020/10/dd9551d8efd1c43e.jpg' />
2、貌似订阅还不能订阅

建议：
1、4人争上游，要是能一直做下去就好了，获胜一次一颗星星。
2、建议挑战答题，搞一个刷题库模式，做个通关，还可以自动保存题库。

如果过于麻烦，请忽略哈。

**Comment by james-bond-007** [comment]
> 感谢大神的付出，辛苦啦
> 系统安卓8.0
> 1、刚发现V2.17.0.4二人答某题出错后，一直卡在80分不动啦，直到别人答100分。
> https://ftp.bmp.ovh/imgs/2020/10/dd9551d8efd1c43e.jpg
> ![](https://camo.githubusercontent.com/1abd9702cfea5ec18e549ed565f27124faae1841/68747470733a2f2f6674702e626d702e6f76682f696d67732f323032302f31302f646439353531643865666431633433652e6a7067)
> 2、貌似订阅还不能订阅
> 
> 建议：
> 1、4人争上游，要是能一直做下去就好了，获胜一次一颗星星。
> 2、建议挑战答题，搞一个刷题库模式，做个通关，还可以自动保存题库。
> 
> 如果过于麻烦，请忽略哈。

谢谢反馈！
图片打不开，您试试直接插入本地图片；订阅设置成周一三五七运行了；对战确实不稳定，还在想解决方案；争上游设计的就是一次两轮；挑战答题可以刷题库，多运行几次，正确率会提高；怕封号，不敢刷通关，没有谁能坚持刷通关，除了程序

**Comment by 85524365** [comment]
感谢回复
