### ISSUE TITLE
部分图库中的题目无法点击

### ISSUE THREAD

**Issue by elevonyao** [james-bond-007/lovexuexi#26]
题目：“在我国，ABO血型系统中，人数比例最高的是 。”
题库中可以找到正确答案是“A和O”，但是每次都无法点击，随机点一个，无法更新答案。
删掉题目，新建题目和答案都无法解决，怀疑是答案中出现相同的“A、和、O”等字符，无法判断出正确答案。

**Comment by elevonyao** [comment]
题目：“下列不属于二十四史的是”
答案：“清史”

以上题目也存在“未能成功点击，随机点击一个”的问题

**Comment by james-bond-007** [comment]
都是答案问题。因为选项或答案发生变化造成的。
题目：“在我国，ABO血型系统中，人数比例最高的是 。”
正确答案改为“A型和O型”。
题目：“下列不属于二十四史的是”
正确答案改为”左传“

解决方法，1、手动改为正确答案；2、删除有答案但答不对的题目，再遇到这个题，程序会自动获取正确答案。
