### ISSUE TITLE
挑战答题出错

### ISSUE THREAD

**Issue by StraightJet** [james-bond-007/lovexuexi#27]
挑战答题的时候如果题库中没有题目就会报错停止运行。
![屏幕截图 2020-11-26 084454](https://user-images.githubusercontent.com/8295648/100297164-0a241180-2fc9-11eb-8444-46d7aff4b150.jpg)
![屏幕截图 2020-11-26 084553](https://user-images.githubusercontent.com/8295648/100297173-0d1f0200-2fc9-11eb-8e89-d1c2b257a216.jpg)

还有个小问题，悬浮窗有时候会消失，但是脚本还在运行，对监控运行状况造成了麻烦，可以的话劳请修复一下。

环境：逍遥模拟器7.2.5
Android版本：7.1.2

**Comment by james-bond-007** [comment]
> 挑战答题的时候如果题库中没有题目就会报错停止运行。
> 
> 还有个小问题，悬浮窗有时候会消失，但是脚本还在运行，对监控运行状况造成了麻烦，可以的话劳请修复一下。
> 
> 环境：逍遥模拟器7.2.5
> Android版本：7.1.2

出现错误的原因是：抓取答题结果时，图像读取出现错误。
是否允许截图了？如果允许截图了，是不是模拟器不支持，换个模拟器？
我没用过模拟器，你再试试吧！欢迎反馈结果。

**Comment by StraightJet** [comment]
找到问题了，需要把渲染模式切换到OpenGL模式，在DirectX模式下没法启动OpenCV（应该是吧）导致报错。
![屏幕截图 2020-11-26 143337](https://user-images.githubusercontent.com/8295648/100316264-19b94f80-2ff5-11eb-8b8d-0ac386645e4d.jpg)

**Comment by james-bond-007** [comment]
> 找到问题了，需要把渲染模式切换到OpenGL模式，在DirectX模式下没法启动OpenCV（应该是吧）导致报错。
> ![屏幕截图 2020-11-26 143337](https://user-images.githubusercontent.com/8295648/100316264-19b94f80-2ff5-11eb-8b8d-0ac386645e4d.jpg)

对，应该是这样子
