### ISSUE TITLE
2.19.0.3及2.19.0.4，安装后无法启动，屡次停止运行

### ISSUE THREAD

**Issue by q914111182** [james-bond-007/lovexuexi#62]
![Screenshot_20201225_100015](https://user-images.githubusercontent.com/16411757/103114019-15399280-4698-11eb-9eb8-d8a44855660f.jpg)

**Comment by james-bond-007** [comment]
重新下载试试吧

**Comment by q914111182** [comment]
感谢您的回复，我在我的三部手机尝试了，一部一加7pro（覆盖安装），一部一加5（全新安装），一部华为X10（全新安装），只有华为能正常运行……氢OS全部停止运行，所有安装包都为全新下载，在包括2.19.0.2及之前版本运行一切正常
