### ISSUE TITLE
建议开源该分支，让更多人参与维护开发，以供参考，不赞同关闭即可

### ISSUE THREAD

**Issue by chu10** [james-bond-007/lovexuexi#64]
作者目前是更新维护比较频繁的一个分支，望开源

**Comment by athunder2020** [comment]
谁提的要求谁去完成吧，不要给邦德大神施加压力了。有错报错，其他要求要么自己完成要么找别人。

**Comment by chu10** [comment]
一个人可以走的很快，一群人可以走的很远。但凡有点动手能力也能得到源码，何苦为了工具而工具，再说也是提建议并没有像你说的要求，感谢你的耐心回复
