### ISSUE TITLE
提几点安全建议

### ISSUE THREAD

**Issue by xuoy** [james-bond-007/lovexuexi#74]
1，建议把学习文章和学习视频的时间再最低完成标准的基础上增加随机学习时间，因为每次都是固定的学习秒数，担心会被查。
2，建议答题，视频和文章 可以随机顺序来学习，每次都是固定的学习顺序，主要还是心虚哈。

**Comment by james-bond-007** [comment]
随机顺序列入计划

**Comment by wanghuisenior** [comment]
我主页的可以随机

**Comment by xuoy** [comment]
感谢作者把两条意见全部实现，现在安全性大大的提高

**Comment by xuoy** [comment]
已经实现
